# Generated by Django 4.2 on 2023-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
